title: Otávio Henrique da Silva Ribeiro
description: Portfolio profissional de Engenharia de Dados e Liderança
url: "https://donotavio.github.io"
baseurl: "/curr-don"
lang: "pt-BR"
markdown: kramdown
permalink: pretty
timezone: America/Sao_Paulo
