title: Ot√°vio Henrique da Silva Ribeiro
description: Site executivo de carreira e projetos
url: "https://SEU_USUARIO.github.io/SEU_REPOSITORIO"
baseurl: ""
lang: "pt-BR"
markdown: kramdown
permalink: pretty
timezone: America/Sao_Paulo
